package com.liato.bankdroid.banking.banks.nordea.api.model;

public enum ErrorCode {
	MAS0002("MAS0002","Your personal code has been blocked."),
	MAS0004("MAS0004","Personal identity number and code do not match."),
	MAS0005("MAS0005","Personal identity number and code do not match."),
	MAS0006("MAS0006","Banking services are not available with this agreement"),
	MAS0009("MAS0009", "An error has occured."),
	MAS0010("MAS0010","Personal code is locked"),
	MAS0011("MAS0011","Personal code is expired"),
	MAS0012("MAS0012","This user is unknown"),
	MAS0013("MAS0013","Light login already activated"),
	MAS0017("MAS0017","No accounts have been registered to your Netbank access."),
	MAS0018("MAS0018","Mobilbank is temporarily closed"),
	MAS0019("MAS0019","You do not have access to Mobilbank. Activate your access to Mobilbank from your Netbank."),
	MAS0020("MAS0020","Your NemID has been blocked."),
	MAS0021("MAS0021","You need NemID to be able to log on"),
	MAS0030("MAS0030","Personal identity number and code do not match."),
	MAS0040("MAS0040","Session max time exeeded, please log in again"),
	MAS9001("MAS9001","There is a technical error. Please try again in a while."),
	MAS9099("MAS9099","There is a technical error. Please log in again."),
	MBS0100("MBS0100","Account cannot be found."),
	MBS1201("MBS1201","No payments or transactions exist"),
	MBS0301("MBS0301","No transactions exist"),
	MBS0302("MBS0302","No transactions exist"),
	MBS0501("MBS0501","Sorry, an error occurred. Please check the status of your transfers in 'Upcoming payments and transfers' and 'Account transactions'."),
	MBS0502("MBS0502","There is insufficient money in the account"),
	MBS0503("MBS0503","Due date for payment cannot be more than 5 years in the future"),
	MBS0504("MBS0504","Please check message"),
	MBS0505("MBS0505","Due date cannot be in past"),
	MBS1506("MBS1506","Transfer already exists"),
	MBS1507("MBS1507","Transfer will be made using the due date exchange rate"),
	MBS1508("MBS1508","One or several payments/transfers have been rejected, and due date has automatically been changed to the following banking day"),
	MBS0509("MBS0509","Amount must be stated in the currency of the from-account if due date is a future date"),
	MBS0510("MBS0510","You are not allowed to make payments/transfers from selected account"),
	MBS1511("MBS1511","Due date is not a banking day and has automatically been changed to the following banking date"),
	MBS0512("MBS0512","Amount exceeded the daily limit"),
	MBS0513("MBS0513","This account is blocked"),
	MBS1514("MBS1514","The exact exchange rate is to be determined"),
	MBS0401("MBS0401","There are no transaction details available"),
	MBS0701("MBS0701","There are no payment details available"),
	MBS0801("MBS0801","The beneficiary could not be found"),
	MBS9001("MBS9001","Temporary system failure. Please try again later."),
	MBS1516("MBS1516","The due date was changed to first possible banking day"),
	MBS1517("MBS1517","The payment exceeds the security limit"),
	MBS1518("MBS1518","Adding of recurrence failed. Please try again."),
	MBS1519("MBS1519","Addition of payee data failed. Please try again."),
	MBS1520("MBS1520","The payee's account number has been converted to an IBAN format"),
	MBS0521("MBS0521","An error occurred. Please check 'Unconfirmed payments'."),
	MBS0522("MBS0522","Sorry, an error occurred. Please check the status of your payments from 'Unconfirmed payments', 'Due payments and transfers' and 'Account transactions'."),
	MBS0523("MBS0523","The payment amount is too big or too small"),
	MBS0524("MBS0524","Please enter the 'To account' number"),
	MBS0525("MBS0525","Please check the 'To account'"),
	MBS0526("MBS0526","Please check the beneficiary's name"),
	MBS0527("MBS0527","Please enter the reference number"),
	MBS0528("MBS0528","Please check the OCR number"),
	MBS0529("MBS0529","A reference number is not allowed"),
	MBS0530("MBS0530","Please enter a message"),
	MBS0531("MBS0531","Please check the message"),
	MBS0532("MBS0532","Message not allowed"),
	MBS0533("MBS0533","Please enter a due date for the payment"),
	MBS0534("MBS0534","Please check the due date for the payment"),
	MBS0535("MBS0535","Please change the payment's due date for tomorrow or to a later date"),
	MBS0536("MBS0536","The payment amount exceeds the daily safety limit"),
	MBS0537("MBS0537","Please check the payment amount. Enter the amount in the format '1234.00'."),
	MBS0538("MBS0538","Please check the number of payments"),
	MBS0539("MBS0539","Please check recurrency"),
	MBS0540("MBS0540","Please check ending date for recurrence"),
	MBS0541("MBS0541","The payment is under processing"),
	MBS0542("MBS0542","Payment closed"),
	MBS0543("MBS0543","Payment cannot be changed"),
	MBS0544("MBS0544","Payment details cannot be changed"),
	MBS0545("MBS0545","The payment has been changed. Please retrieve it again."),
	MBS0546("MBS0546","The payment exceeds the security limit"),
	MBS0547("MBS0547","Please check the beneficiary's name"),
	MBS0548("MBS0548","SEPA credit transfers are not accepted by beneficiary's bank, please make the payment as cross-border payment"),
	MBS0549("MBS0549","Enter reference number or message"),
	MBS0550("MBS0550","You have already saved a beneficiary under this name in the Beneficiary register. Save the beneficiary using another name."),
	MBS0551("MBS0551","Payments with OCR code can only be made in SEK"),
	MBS0552("MBS0552","You cannot make two identical payments or transfers"),
	MBS0553("MBS0553","This service requires that you have at least two valid accounts to transfer funds between"),
	MBS0012("MBS0012","Sorry, an error occurred. Please try again."),
	MBS0101("MBS0101","There is no access to the requested function."),
	MBS0202("MBS0202","There is no access to the requested function."),
	MBS0515("MBS0515","An unknown error has occurred. Please try again."),
	MBS0554("MBS0554","Incorrect account number or The account does not exist and thus the " +
			"transfer has not been executed. You can change the account number. " +
			"The account to be debited does not exist and thus the transfer has not been " +
			"executed. The account to be debited has been cancelled and thus the transfer " +
			"has not been executed. You can choose another account. " +
			"You do not have access to the account."),
    MBS0555("MBS0555","The account to be debited/credited has been blocked and thus the transfer has not been executed. You can choose another account."),
    MBS0556("MBS0556","The amount cannot exceed 9,999,999.99 kr. Correct the amount and try again. Incorrect amount. The amount can not be zero."),
    MBS0557("MBS0557","There is no access to the requested function."),
    MBS0558("MBS0558","No payment due date. We have chosen the next possible due date"),
    MBS0559("MBS0559","The cut-off time for payment today has passed. We have chosen the next possible due date"),
    MBS0560("MBS0560","The payment date has been exceeded. Correct the date and try again."),
    MBS0561("MBS0561","The account to be debited cannot be identical to the account to be credited"),
    MBS0562("MBS0562","Incorrect account number or The account does not exist and thus the " +
    		"transfer has not been executed. You can change the account number. " +
    		"The account to be debited does not exist and thus the transfer has not been " +
    		"executed. The account to be debited has been cancelled and thus the transfer " +
    		"has not been executed. You can choose another account. " +
    		"You do not have access to the account."),
    MBS0563("MBS0563","Incorrect beneficiary's branch ID. The transfer has not been executed. You can change the branch ID"),
    MBS0564("MBS0564","The beneficiary's account has been blocked and the transfer has " +
    		"not been executed. You can change the account number. " +
    		"The beneficiary's account does not exist any more and thus the transfer has " +
    		"not been executed. You can choose another account."),
    MBS0565("MBS0565","The account to be debited/credited has been blocked and thus the transfer has not been executed. You can choose another account."),
    MBS0566("MBS0566","Giro/Creditor number cannot be used together with the form type/payment ID. Please change the form type/payment ID."),
    MBS0567("MBS0567","The amount cannot exceed 9,999,999.99 kr. Correct the amount and try again. Incorrect amount. The amount can not be zero."),
    MBS0568("MBS0568","There is no access to the requested function."),
    MBS0569("MBS0569","The requested transfer has already been registered in Netbank. The message has been received before."),
    MBS0570("MBS0570","Creditor number/form type not recognised"),
    MBS0571("MBS0571","No payment due date. We have chosen the next possible due date."),
    MBS0572("MBS0572","The cut-off time for payment today has passed. We have chosen the next possible due date."),
    MBS0573("MBS0573","You have not entered the payment ID correctly. Please verify that you have entered the digits exactly as they appear on the transfer form."),
    MBS0574("MBS0574","The beneficiary's account cannot be the account to debet"),
    MBS0575("MBS0575","Incorrect bank sort code / account number - try again"),
    MBS0576("MBS0576","This year the maximum contribution is {1}. You have paid {2} and thus cannot pay more than an additional: {3}"),
    MBS0577("MBS0577","The selected account can't be used for transfers and payments"),
    MBS0578("MBS0578","Creditor number/form type not recognised"),
    MBS0601("MBS0601","The confirmation code is incorrect, please try again"),
    MBS0602("MBS0602","Response code is wrong or filled in too late (the challenge is timed out)"),
    MBS9099("MBS9099","Sorry, an error occurred. Please try again."),
    MAS0601("MAS0601","The confirmation code is incorrect, please try again"),
    MBS0000("MBS0000","OK"),
    MBS0010("MBS0010","Sorry, an error occurred. Please try again."),
    MBS0011("MBS0011","Sorry, an error occurred. Please try again."),
    MBS0015("MBS0015","Sorry, an error occurred. Please try again."),
    MBS0016("MBS0016","Sorry, an error occurred. Please try again."),
    MBS0802("MBS0802","You have already saved a beneficiary under this name in the Beneficiary register. Please save the beneficiary using another name."),
    MBS0803("MBS0803","A beneficiary with the given short name already exists"),
    UNKNOWN("Unknown","Sorry, an error occurred. Please try again."),
    MAS9098("MAS9098","The app needs to be updated in order to work"),
    MAS9097("MAS9097","Sorry, an error occurred. Please try again."),
    MBS0579("MBS0579","The beneficiary account doesn't match the selected bank."),
    MBS0580("MBS0580","Please, fill in beneficiary bank id"),
    MBS0581("MBS0581","Only SEK is allowed when transferring to another bank"),
    MBS0582("MBS0582","Check currency"),
    MBS1583("MBS1583","OCR code contains errors"),
    MBS0584("MBS0584","You can not make a payment / transfer to the designated receiving account."),
    MAS0031("MAS0031","Personal identity number and code do not match. Please verify what you have entered and try again."),
    MBS0804("MBS0804","You have saved the maximum number of personal beneficiarys. Try deleting some for more space."),
    MBS0585("MBS0585","Check the payment's value date"),
    MBS0586("MBS0586","The selected currency can't be used"),
    MBS0587("MBS0587","You must enter a name for the saved receiver"),
    MBS0588("MBS0588","Bank account numbers in some banks must be formated a certain way"),
    MBS1100("MBS1100","You don't have accounts for this service"),
    MBS0589("MBS0589","Not possible to do transfers with future dates"),
    MBS0702("MBS0702","No permission to modify payment"),
    MBS0703("MBS0703","No permission to change recurring payment"),
    MBS0704("MBS0704","No permission to change amount"),
    MBS0705("MBS0705","No permission to change beneficiary name"),
    MBS0706("MBS0706","No permission to change beneficiary nickname"),
    MBS0707("MBS0707","No permission to change due date"),
    MBS0708("MBS0708","No permission to change From account"),
    MBS0709("MBS0709","No permission to change message"),
    MBS0710("MBS0710","No permission to change payment type"),
    MBS0711("MBS0711","No permission to change reference number"),
    MBS0712("MBS0712","No permission to change reference number with eInvoice, DirectDebit and SepaDirectDebit"),
    MBS0713("MBS0713","No permission to change recipient account"),
    MBS0714("MBS0714","No permission to make transfer from account"),
    MBS0715("MBS0715","No permission to make transfer to account"),
    MAS0602("MAS0602","Sorry, an error occurred"),
    MAS0031_Android("MAS0031_Android","The user ID and the password do not match.");
    
    		
	
	
	private final String mErrorCode;
	private final String mErrorMessage;
	
	private ErrorCode(String pCode, String pErrorMessage) {
		mErrorCode = pCode;
		mErrorMessage = pErrorMessage;
	}
}
