package com.liato.bankdroid.banking;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;

import com.liato.bankdroid.banking.banks.AkeliusInvest;
import com.liato.bankdroid.banking.banks.AkeliusSpar;
import com.liato.bankdroid.banking.banks.AmericanExpress;
import com.liato.bankdroid.banking.banks.AppeakPoker;
import com.liato.bankdroid.banking.banks.Audi;
import com.liato.bankdroid.banking.banks.AvanzaMini;
import com.liato.bankdroid.banking.banks.BetterGlobe;
import com.liato.bankdroid.banking.banks.Bioklubben;
import com.liato.bankdroid.banking.banks.BlekingeTrafiken;
import com.liato.bankdroid.banking.banks.BrummerKF;
import com.liato.bankdroid.banking.banks.CSN;
import com.liato.bankdroid.banking.banks.Chalmrest;
import com.liato.bankdroid.banking.banks.Chevrolet;
import com.liato.bankdroid.banking.banks.DinersClub;
import com.liato.bankdroid.banking.banks.Djurgarden;
import com.liato.bankdroid.banking.banks.EasyCard;
import com.liato.bankdroid.banking.banks.EurobonusMastercard;
import com.liato.bankdroid.banking.banks.EurobonusMastercardDk;
import com.liato.bankdroid.banking.banks.EurobonusMastercardNo;
import com.liato.bankdroid.banking.banks.Eurocard;
import com.liato.bankdroid.banking.banks.Everydaycard;
import com.liato.bankdroid.banking.banks.FirstCard;
import com.liato.bankdroid.banking.banks.ForexBank;
import com.liato.bankdroid.banking.banks.Handelsbanken;
import com.liato.bankdroid.banking.banks.Hemkop;
import com.liato.bankdroid.banking.banks.IKEA;
import com.liato.bankdroid.banking.banks.IkanoBank;
import com.liato.bankdroid.banking.banks.Jojo;
import com.liato.bankdroid.banking.banks.Marginalen;
import com.liato.bankdroid.banking.banks.McDonalds;
import com.liato.bankdroid.banking.banks.Meniga;
import com.liato.bankdroid.banking.banks.NordeaDK;
import com.liato.bankdroid.banking.banks.Nordnet;
import com.liato.bankdroid.banking.banks.Nordnetdirekt;
import com.liato.bankdroid.banking.banks.OKQ8;
import com.liato.bankdroid.banking.banks.Opel;
import com.liato.bankdroid.banking.banks.Ostgotatrafiken;
import com.liato.bankdroid.banking.banks.Osuuspankki;
import com.liato.bankdroid.banking.banks.PayPal;
import com.liato.bankdroid.banking.banks.PlusGirot;
import com.liato.bankdroid.banking.banks.Preem;
import com.liato.bankdroid.banking.banks.Quintessentially;
import com.liato.bankdroid.banking.banks.ResursBank;
import com.liato.bankdroid.banking.banks.SJPrio;
import com.liato.bankdroid.banking.banks.Saab;
import com.liato.bankdroid.banking.banks.Seat;
import com.liato.bankdroid.banking.banks.SevenDay;
import com.liato.bankdroid.banking.banks.Shell;
import com.liato.bankdroid.banking.banks.Skandiabanken;
import com.liato.bankdroid.banking.banks.Skoda;
import com.liato.bankdroid.banking.banks.SparbankenSyd;
import com.liato.bankdroid.banking.banks.Statoil;
import com.liato.bankdroid.banking.banks.SupremeCard;
import com.liato.bankdroid.banking.banks.SveaDirekt;
import com.liato.bankdroid.banking.banks.SvenskaSpel;
import com.liato.bankdroid.banking.banks.TestBank;
import com.liato.bankdroid.banking.banks.TicketRikskortet;
import com.liato.bankdroid.banking.banks.TrustBuddy;
import com.liato.bankdroid.banking.banks.Vasttrafik;
import com.liato.bankdroid.banking.banks.Villabanken;
import com.liato.bankdroid.banking.banks.Volkswagen;
import com.liato.bankdroid.banking.banks.Volvofinans;
import com.liato.bankdroid.banking.banks.Wallet;
import com.liato.bankdroid.banking.banks.Zidisha;
import com.liato.bankdroid.banking.banks.avanza.Avanza;
import com.liato.bankdroid.banking.banks.bitcoin.Bitcoin;
import com.liato.bankdroid.banking.banks.coop.Coop;
import com.liato.bankdroid.banking.banks.ica.ICA;
import com.liato.bankdroid.banking.banks.icabanken.ICABanken;
import com.liato.bankdroid.banking.banks.lansforsakringar.Lansforsakringar;
import com.liato.bankdroid.banking.banks.nordea.Nordea;
import com.liato.bankdroid.banking.banks.payson.Payson;
import com.liato.bankdroid.banking.banks.rikslunchen.Rikslunchen;
import com.liato.bankdroid.banking.banks.seb.SEB;
import com.liato.bankdroid.banking.banks.swedbank.Sparbankerna;
import com.liato.bankdroid.banking.banks.swedbank.Swedbank;

import java.util.ArrayList;

public class LegacyBankFactory {


    public static ArrayList<Bank> listBanks(Context context) {
        ArrayList<Bank> banks = new ArrayList<Bank>();
        banks.add(new AkeliusInvest(context));
        banks.add(new AkeliusSpar(context));
        banks.add(new TrustBuddy(context));
        banks.add(new BrummerKF(context));
        banks.add(new Swedbank(context));
        banks.add(new Nordea(context));
        banks.add(new ICABanken(context));
        banks.add(new Lansforsakringar(context));
        banks.add(new Handelsbanken(context));
        banks.add(new Coop(context));
        banks.add(new ICA(context));
        banks.add(new Statoil(context));
        banks.add(new Avanza(context));
        banks.add(new Villabanken(context));
        banks.add(new AvanzaMini(context));
        banks.add(new OKQ8(context));
        banks.add(new Eurocard(context));
        banks.add(new FirstCard(context));
        banks.add(new PayPal(context));
        banks.add(new Payson(context));
        banks.add(new Jojo(context));
        //banks.add(new Steam(context));
        banks.add(new DinersClub(context));
        banks.add(new IkanoBank(context));
        banks.add(new EurobonusMastercard(context));
        banks.add(new Rikslunchen(context));
        banks.add(new Hemkop(context));
        banks.add(new SEB(context));
        banks.add(new Nordnet(context));
        banks.add(new SevenDay(context));
        banks.add(new Osuuspankki(context));
        banks.add(new Volvofinans(context));
        banks.add(new CSN(context));
        banks.add(new ResursBank(context));
        banks.add(new McDonalds(context));
        banks.add(new SJPrio(context));
        banks.add(new SparbankenSyd(context));
//        banks.add(new SparbankenOresund(context));
        banks.add(new Opel(context));
        banks.add(new Skandiabanken(context));
        banks.add(new AmericanExpress(context));
        banks.add(new PlusGirot(context));
        banks.add(new Nordnetdirekt(context));
        banks.add(new Saab(context));
        banks.add(new Wallet(context));
        banks.add(new Chevrolet(context));
        banks.add(new Djurgarden(context));
        banks.add(new Quintessentially(context));
        banks.add(new Shell(context));
        banks.add(new Volkswagen(context));
        banks.add(new Audi(context));
        banks.add(new Preem(context));
        banks.add(new Seat(context));
        banks.add(new Skoda(context));
        banks.add(new IKEA(context));
//        banks.add(new DanskeBank(context));
        banks.add(new NordeaDK(context));
        banks.add(new Vasttrafik(context));
        banks.add(new Everydaycard(context));
        banks.add(new Meniga(context));
        banks.add(new TicketRikskortet(context));
        banks.add(new Bioklubben(context));
        banks.add(new Chalmrest(context));
        banks.add(new Marginalen(context));
        banks.add(new SvenskaSpel(context));
        banks.add(new EasyCard(context));
        banks.add(new AppeakPoker(context));
        banks.add(new Zidisha(context));
        banks.add(new BetterGlobe(context));
        banks.add(new ForexBank(context));
        banks.add(new EurobonusMastercardNo(context));
        banks.add(new Bitcoin(context));
        banks.add(new EurobonusMastercardDk(context));
        banks.add(new SveaDirekt(context));
        banks.add(new SupremeCard(context));
        banks.add(new Sparbankerna(context));
        banks.add(new BlekingeTrafiken(context));
        banks.add(new Ostgotatrafiken(context));

        SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(context);
        if (prefs.getBoolean("debug_mode", false)) {
            banks.add(new TestBank(context));
        }
        return banks;
    }
}
